# Generated by Django 2.1.4 on 2018-12-24 07:51

from django.db import migrations
import mapping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medimage',
            name='image',
            field=mapping.fields.ThumbnailImageField(upload_to='medimage/%Y/%m'),
        ),
    ]
