# Generated by Django 2.1.4 on 2018-12-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0002_auto_20181224_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medimage',
            name='request_time',
            field=models.TimeField(auto_now_add=True, verbose_name='Request Date'),
        ),
    ]
