# Generated by Django 2.1.4 on 2018-12-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0003_auto_20181224_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medimage',
            name='request_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Request Date'),
        ),
    ]
