# Generated by Django 2.1.4 on 2018-12-24 08:21

from django.db import migrations
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0004_auto_20181224_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medimage',
            old_name='image',
            new_name='dicom_jpg_file',
        ),
        migrations.AlterField(
            model_name='medimage',
            name='request_time',
            field=django_unixdatetimefield.fields.UnixDateTimeField(auto_now_add=True, verbose_name='Request Date'),
        ),
    ]
