# Generated by Django 2.1.4 on 2018-12-24 08:24

from django.db import migrations
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0006_auto_20181224_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medimage',
            name='request_time',
            field=django_unixdatetimefield.fields.UnixDateTimeField(auto_now_add=True, verbose_name='Request Date'),
        ),
    ]
