# Generated by Django 2.1.4 on 2018-12-26 16:20

from django.db import migrations, models
import mapping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0009_auto_20181224_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medimage',
            name='emr_file',
        ),
        migrations.RemoveField(
            model_name='medimage',
            name='pacs_file',
        ),
        migrations.AlterField(
            model_name='medimage',
            name='dicom_jpg_file',
            field=mapping.fields.ThumbnailImageField(upload_to='dicom_jpg/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='medimage',
            name='progress',
            field=models.IntegerField(verbose_name='Viewing Progress'),
        ),
    ]
